export interface User {
  id: number;
  twitchId: number;
  displayName: string;
  created: number;
  avatar: string;
  avatarWEBP: string;
  avatarJP2: string;
  profileUrl: string;
  gsiAuth: string;
  dotaStatsFrom: string;
  dotaStatsMenuHidden: boolean;
  dotaStatsPickHidden: boolean;
  useBets: boolean;
  betSeasonId: number | null;
  gsiConnected: boolean;
  frameApiKey: string;
  gsiActive: boolean;
  status: "active" | "disabled";
  streamDelay: number;
  teamAName: string;
  teamBName: string;
  useAutomaticVoting: boolean;
  keywordListener: string | null;
  useKeywordListener: boolean;
  individualOverlayVoteDistribution: boolean;
  individualOverlayVoteToplist: boolean;
  individualOverlayVoteTimer: boolean;
  individualOverlayWLStats: boolean;
  individualOverlayMinimap: boolean;
  individualOverlayDraftStats: boolean;
  individualOverlayVoteHeroStats: boolean;
  individualOverlayRoshTimer: boolean;
  useDotaStatsOverlay: boolean;
  useMinimapOverlay: boolean;
  useRoshanTimerOverlay: boolean;
  useDraftStatsOverlay: boolean;
  useHeroStatsOverlay: boolean;
  useVoteToplistOverlay: boolean;
  useVoteTimerOverlay: boolean;
  useVoteDistributionOverlay: boolean;
  useKeywordListenerOverlay: boolean;
  castingStatsSource: null | string;
  usePredictions: boolean;
  predictionDuration: number;
  hasPredictionAccess: number;
  predictionPlayingTitle: string;
  predictionPlayingOptionA: string;
  predictionPlayingOptionB: string;
  predictionObservingTitle: string;
  predictionObservingOptionA: string;
  predictionObservingOptionB: string;
}
